name: CI Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.16.0"

      - name: Install dependencies
        run: |
          cd tdw-beatriz # Navigate to your Next.js project folder
          npm install

      - name: Run Lint
        run: |
          cd tdw-beatriz  # Navigate to your Next.js project folder
          npm run lint

  build:
    runs-on: ubuntu-latest
    needs: lint # Ensure this job runs only after the lint job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.16.0" # Match Node.js version with the lint job

      - name: Install dependencies
        run: |
          cd tdw-beatriz # Navigate to your Next.js project folder
          npm install

      - name: Build Project
        run: |
          cd tdw-beatriz # Navigate to your Next.js project folder
          npm run build
        if: success() && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')

  deploy:
    runs-on: ubuntu-latest
    needs: build # Ensure this job runs only after the build job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.16.0" # Match Node.js version with previous jobs

      - name: Install dependencies
        run: |
          cd tdw-beatriz # Navigate to your Next.js project folder
          npm install

      - name: Deploy to Netlify
        run: |
          cd tdw-beatriz # Navigate to your Next.js project folder
          npx netlify-cli deploy --site lovely-vacherin-731d1e.netlify.app --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --prod
        if: success() && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
