name: Lint

on: push

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      # Update checkout to v3
      - name: Check out Git repository
        uses: actions/checkout@v3

      # Node.js setup already using v3, no change needed here
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      # Install dependencies
      - name: Install Node.js dependencies
        run: npm install
        working-directory: ./tdw-beatriz

      # Run the linters using a lint action
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          eslint: true
          prettier: true
