name: Lint

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.16.0"

      - name: Install dependencies
        run: |
          cd tdw-beatriz # Navigate to your Next.js project folder
          npm install

      - name: Run Lint
        run: |
          cd tdw-beatriz  # Navigate to your Next.js project folder
          npm run lint

      - name: Build Project
        run: npm run build
        if: success() && github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'

      # - name: Coveralls GitHub Action
      #   uses: coverallsapp/github-action@v2.3.0
